# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a Node.js image
FROM node:16-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code
COPY src ./src

# Copy the TypeScript configuration
COPY tsconfig.json ./

# Build the TypeScript project
RUN npm run build

# Final stage for running
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy the built files from the builder
COPY --from=builder /app/build ./build

# Copy package.json and package-lock.json for runtime dependencies
COPY package.json package-lock.json ./

# Install production dependencies
RUN npm ci --only=production

# Define the environment variable for the NewsAPI key
ENV NEWS_API_KEY=your-api-key-here

# Set the entry point for the container
ENTRYPOINT ["node", "build/index.mjs"]
